#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
    This module is usefull to download files faster than usual.
    It split the file into parts and download each part on different process
"""

__version__ = "1.0.0"

from multi_process_downloader import Downloader