#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
    This module is usefull to download files faster than usual.
    It split the file into parts and download each part on different process
"""

name = "mdwpy"

__version__ = "1.2.0"

from mdwpy.downloader import Downloader